name: Crawl Dak.gg

on:
  schedule:
    - cron: '0 15,19,23,3,7,11 * * *'  # 한국시간 00, 04, 08, 12, 16, 20시 -> UTC 15, 19, 23, 03, 07, 11시
  workflow_dispatch:  # 수동 실행도 가능하게 함

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ 푸시 권한 포함

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: 크롤링 실행
        run: python crawl_dakgg.py

      - name: 결과 파일 커밋 및 푸시
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # 루트 디렉토리의 versions.json을 포함시켜 푸시
          git add versions.json data/
          
          git diff --cached --quiet && echo "변경사항 없음, 푸시 생략" || (
            git commit -m "자동 업데이트: 티어별 통계 저장"
            git push
          )
