name: Crawl Dak.gg

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 파이썬 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps

      - name: 크롤링 실행
        run: python crawl_dakgg.py

      - name: 결과 파일 커밋 및 푸시
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --cached --quiet && echo "변경사항 없음, 푸시 생략" || (
            git commit -m "자동 업데이트: 크롤링 결과"
            git push
          )
